### ISSUE TITLE
Address "overlapping" warnings

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pycds#94]
We're getting warnings while running `crmprtd` (against the main `crmp` database).

> ``` /storage/home/crmprtd/env_3.2.3/lib64/python3.6/site-packages/sqlalchemy/orm/relationships.py:3463: SAWarning: relationship 'Variable.obs' will copy column meta_vars.vars_id to column obs_raw.vars_id, which conflicts with relationship(s): 'Variable.obs_raw' (copies meta_vars.vars_id to obs_raw.vars_id), 'Obs.variable' (copies meta_vars.vars_id to obs_raw.vars_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning. (Background on this error at: http://sqlalche.me/e/14/qzyx)```

Investigate and decide whether we need to address this (or remove the warning).

**Comment by rod-glover** [comment]
There are 12 such warnings issued for PyCDS. They come in pairs due to how PyCDS defines the relationships between tables. Therefore there are apparently 6 independent problems.

**Comment by rod-glover** [comment]
Let's take the quoted warning as an example case.

The root of the problem is that classes `Variable` and `Obs` _both_ define
the relationship between them using `backref`. Documentation indicates `backref`
must be used on only one side of the relationship; the other side is created
automatically with the name specified by its first arg.

```
class Variable(Base):
    __tablename__ = "meta_vars"
    id = Column("vars_id", Integer, primary_key=True)
    ...
    obs = relationship("Obs", backref=backref("meta_vars", order_by=id))
    ...



class Obs(Base):
    __tablename__ = "obs_raw"
    id = Column("obs_raw_id", BigInteger, primary_key=True)
    ...
    variable = relationship("Variable", backref=backref("obs_raw", order_by=id))
    ...
```

The fix is one of two options:

1. Define the relationship only from one side using `backref`:
   - Remove relationship `obs = ...` from `Variable` (confirmed), OR
     - Removes relationship `Obs.meta_vars`
   - Remove relationship `variable = ...` from `Obs` (confirmed)
     - Removes relationship `Variable.obs_raw`
2. Define the relationship from both sides using `back_populates`.  (confirmed)
   - Removes relationships `Obs.meta_vars`, `Variable.obs_raw`

Both these introduce a potential breaking change by removing at least one of 
the redundant names for the relationships
- `Obs.variable` / `Obs.meta_vars`
- `Variable.obs` / `Variable,obs_raw`

If we choose option 2, we need to include `order_by` in the defintion
of `Variable.obs` to remain consistent with the existing code.

(Note: This review also reveals that the definitions of the many:1 relationship
`Obs.meta_vars` is if not incorrect, then misleading, as it includes
an `order_by` parameter that is appropriate only for 1:many relationships.)

I prefer option 2 because it makes relationships visible in the declarations 
of both classes. Option 1 requires one to scan the entire set of declarations
in order to know what relationships might be defined for a given class.

**Comment by rod-glover** [comment]
To prevent breaking existing code, we can construct synonyms for the removed relationship names. E.g.,

```
class Variable(Base):
    __tablename__ = "meta_vars"
    id = Column("vars_id", Integer, primary_key=True)
    ...
    obs = relationship("Obs", back_populates="variable", order_by="Obs.id")
    obs_raw = sqlalchemy.orm.synonym("obs")
    ...
```

(confirmed)

**Comment by jameshiebert** [comment]
I'd prefer option 2 as well, for the reasons you state.
